### PR TITLE
Sort includes

### PR DESCRIPTION
**Pull request by dogoepp**
@costashatz @jbmouret @vassilisvas could you please test if it works on your computer before I can merge ?

There used to be problems on my computer.

### CODE REVIEW

**Comment by costashatz** [comment]
I will test if it works, but as far as I remember we did not want to sort the includes automatically. Because for example in limbo, we have a convention for putting the includes (e.g. first the std ones, afterwards the limbo ones, etc).. Correct me if I remember wrong..

**Comment by jbmouret** [comment]
That is indeed the convention.
(std::, boost::, limbo::).

-- JBM

**Comment by costashatz** [comment]
So we should close this right?

**Comment by dogoepp** [comment]
I agree, we did not want to sort the includes. However, this option was 
not accepted by my version of clang-format when I first tried. I would 
like to be sure that we all moved to a version that accepts it.

**Comment by costashatz** [comment]
It is not working for clang-format 3.6... The one that I am using..

**Comment by dogoepp** [comment]
Here we go. Which OS version do you have ? Can you update clang-format ?

My worry with this incompatibility is that it might make a lot of mess if some of us don't have the SortIncludes option available.

**Comment by costashatz** [comment]
> My worry with this incompatibility is that it might make a lot of mess if some of us don't have the SortIncludes option available.

So it is mandatory for some versions and not working for others?

> Which OS version do you have ? Can you update clang-format ?

Xubunut 15.04.. I am sure I can find some PPA.. In which version this should work?

**Comment by dogoepp** [comment]
> So it is mandatory for some versions and not working for others?

Could you test whether your version messes with the includes ?

> In which version this should work?

It works on 3.9. I couldn't find a reference to it in previous versions.

**Comment by costashatz** [comment]
> Could you test whether your version messes with the includes ?

In my version, if it is there, it then ignores all the style file..

> It works on 3.9. I couldn't find a reference to it in previous versions.

We should not put this option yet.. And as we already discussed above, we do not really want it..

**Comment by dogoepp** [comment]
So, do you mean that by default your clang-format does not sort includes 
? On my version, it does by default sort includes, so I need this option.

**Comment by costashatz** [comment]
> So, do you mean that by default your clang-format does not sort includes
> ? On my version, it does by default sort includes, so I need this option.

I did not have any problems. Checked again. It does not sort includes by default..

**Comment by dogoepp** [comment]
So we'll need the user to make changes depending on the version of 
clang-format.

**Comment by costashatz** [comment]
> So we'll need the user to make changes depending on the version of
> clang-format.

I guess so..

**Comment by dogoepp** [comment]
I hope the notice in the README is enough...

**Pull request closed without merging**
